# Nixpacks Configuration für Railway
# Alternative zum Dockerfile - einfacher für Railway

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .next/standalone/server.js"

